version: '3.4'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_hotel_booking_local
    ports:
      - "3307:3306"
    env_file:
      - .env.local
    volumes:
      - ../volumes/db/local:/var/lib/mysql
    networks:
      - hotel_booking_net


networks:
  hotel_booking_net:
    driver: bridge
